name: Build, Tag & Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions:
  contents: write  # Needed to push tags

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Generate release tag
      id: create_tag
      run: |
        VERSION="v$(date +'%Y.%m.%d.%H%M')"
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag "$VERSION"
        git push https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }} "$VERSION"
        echo "tag=$VERSION" >> $GITHUB_OUTPUT
        
    - name: List APKs
      run: find app/build/outputs -name "*.apk"

    - name: Check APK exists
      run: test -f app/build/outputs/apk/release/app-release-unsigned.apk.apk

    - name: Upload release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        files: app/build/outputs/apk/release/app-release-unsigned.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
